# Generated by Django 5.0.4 on 2026-04-28 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0004_aiconversation_aiconversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='analyzer',
            field=models.CharField(db_index=True, help_text='e.g. churn_predictor, risk_alert, hv_churn_outcome', max_length=50, verbose_name='Analyzer'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='model',
            field=models.CharField(help_text='e.g. gpt-4o-mini', max_length=100, verbose_name='AI Model'),
        ),
        migrations.AlterField(
            model_name='alertresolution',
            name='alert_type',
            field=models.CharField(choices=[('overdue', 'Overdue Payment'), ('risk', 'Credit Risk'), ('low_stock', 'Low Stock'), ('sales_drop', 'Sales Drop'), ('high_receivables', 'High Receivables'), ('churn', 'Churn Risk'), ('dso', 'DSO Alert'), ('concentration', 'Client Concentration Risk')], max_length=50, verbose_name='Alert Type'),
        ),
    ]
