# Generated by Django 5.0.6 on 2026-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesession',
            options={'ordering': ['-last_activity'], 'verbose_name': 'Active Session', 'verbose_name_plural': 'Active Sessions'},
        ),
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'Login Attempt', 'verbose_name_plural': 'Login Attempts'},
        ),
        migrations.AlterModelOptions(
            name='refreshtokenrotation',
            options={'ordering': ['-rotated_at'], 'verbose_name': 'Refresh Token Rotation', 'verbose_name_plural': 'Refresh Token Rotations'},
        ),
        migrations.AlterModelOptions(
            name='tokenblacklist',
            options={'ordering': ['-revoked_at'], 'verbose_name': 'Blacklisted Token', 'verbose_name_plural': 'Blacklisted Tokens'},
        ),
        migrations.AlterField(
            model_name='activesession',
            name='device_fingerprint',
            field=models.CharField(help_text='Hashed fingerprint of the device (User-Agent + other data).', max_length=255),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='device_name',
            field=models.CharField(blank=True, help_text='Human-readable device name (e.g. Chrome on Windows).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='IP address at login time.'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Indicates whether this is the active session for the current request.'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='Last activity detected on this session.'),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='refresh_token_jti',
            field=models.CharField(db_index=True, help_text='JTI of the refresh token linked to this session.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email used during the attempt (even if the user does not exist).', max_length=254),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('invalid_credentials', 'Invalid credentials'), ('account_pending', 'Account pending approval'), ('account_rejected', 'Account rejected'), ('account_suspended', 'Account suspended'), ('rate_limited', 'Too many attempts')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='refreshtokenrotation',
            name='new_token_jti',
            field=models.CharField(help_text='JTI of the new refresh token generated after rotation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='refreshtokenrotation',
            name='old_token_jti',
            field=models.CharField(help_text='JTI (JWT ID) of the old refresh token revoked during rotation.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenblacklist',
            name='expires_at',
            field=models.DateTimeField(help_text='Token expiry date. Used for automatic cleanup via Celery.'),
        ),
        migrations.AlterField(
            model_name='tokenblacklist',
            name='reason',
            field=models.CharField(choices=[('logout', 'Logout'), ('logout_all', 'Logout from all devices'), ('password_changed', 'Password changed'), ('password_reset', 'Password reset'), ('admin_revoked', 'Revoked by administrator'), ('suspicious_activity', 'Suspicious activity detected'), ('token_reuse', 'Old token reused')], default='logout', max_length=100),
        ),
        migrations.AlterField(
            model_name='tokenblacklist',
            name='token_jti',
            field=models.CharField(db_index=True, help_text='Unique JWT ID of the revoked token.', max_length=255, unique=True),
        ),
    ]
