# Generated by Django 5.0.4 on 2026-04-28 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_current_stock_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorysnapshotline',
            options={'ordering': ['product_code', 'branch_name'], 'verbose_name': 'Inventory Line', 'verbose_name_plural': 'Inventory Lines'},
        ),
        migrations.AlterField(
            model_name='inventorysnapshotline',
            name='company_name',
            field=models.CharField(help_text='Name of the company that owns this inventory row.', max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='inventorysnapshotline',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 28, 13, 29, 35, 776558, tzinfo=datetime.timezone.utc), verbose_name='Uploaded At'),
            preserve_default=False,
        ),
    ]
