# Generated by Django 5.0.4 on 2026-06-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='True after the manager clicks the verification link in their inbox. Required BEFORE the admin review step. Not to be confused with is_verified (set by admin on approval).', verbose_name='Email address verified'),
        ),
    ]
