# Generated by Django 5.0.4 on 2026-04-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_notification_per_company',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_company_df0aba_idx',
            old_name='notif_company_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_company_0a4c3f_idx',
            old_name='notif_company_type_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['frontend_id'], name='notificatio_fronten_7b7491_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('frontend_id', ''), _negated=True), fields=('company_id', 'frontend_id'), name='unique_notification_per_company'),
        ),
    ]
